--inserting countries into countries

DELETE FROM countries;

DROP SEQUENCE countries_seq;
CREATE SEQUENCE countries_seq START WITH 1 INCREMENT BY 1 MAXVALUE 246;

INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('AF', 'Afghanistan' );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('AL', 'Albania'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('DZ', 'Algeria'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('DS', 'American Samoa'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('AD', 'Andorra'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('AO', 'Angola'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('AI', 'Anguilla'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('AQ', 'Antarctica'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('AG', 'Antigua and Barbuda'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('AR', 'Argentina'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('AM', 'Armenia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('AW', 'Aruba'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('AU', 'Australia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('AT', 'Austria'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('AZ', 'Azerbaijan'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BS', 'Bahamas'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BH', 'Bahrain'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BD', 'Bangladesh'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BB', 'Barbados'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BY', 'Belarus'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BE', 'Belgium'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BZ', 'Belize'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BJ', 'Benin'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BM', 'Bermuda'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BT', 'Bhutan'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BO', 'Bolivia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BA', 'Bosnia and Herzegovina'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BW', 'Botswana'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BV', 'Bouvet Island'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BR', 'Brazil'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('IO', 'British Indian Ocean Territory'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BN', 'Brunei Darussalam'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BG', 'Bulgaria'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BF', 'Burkina Faso'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('BI', 'Burundi'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('KH', 'Cambodia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CM', 'Cameroon'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CA', 'Canada'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CV', 'Cape Verde'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('KY', 'Cayman Islands'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CF', 'Central African Republic'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TD', 'Chad'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CL', 'Chile'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CN', 'China'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CX', 'Christmas Island'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CC', 'Cocos (Keeling) Islands'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CO', 'Colombia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('KM', 'Comoros'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CG', 'Congo'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CK', 'Cook Islands'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CR', 'Costa Rica'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('HR', 'Croatia (Hrvatska)'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CU', 'Cuba'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CY', 'Cyprus'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CZ', 'Czech Republic'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('DK', 'Denmark'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('DJ', 'Djibouti'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('DM', 'Dominica'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('DO', 'Dominican Republic'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TP', 'East Timor'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('EC', 'Ecuador'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('EG', 'Egypt'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SV', 'El Salvador'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GQ', 'Equatorial Guinea'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('ER', 'Eritrea'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('EE', 'Estonia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('ET', 'Ethiopia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('FK', 'Falkland Islands (Malvinas)'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('FO', 'Faroe Islands'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('FJ', 'Fiji'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('FI', 'Finland'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('FR', 'France'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('FX', 'France, Metropolitan'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GF', 'French Guiana'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('PF', 'French Polynesia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TF', 'French Southern Territories'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GA', 'Gabon'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GM', 'Gambia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GE', 'Georgia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('DE', 'Germany'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GH', 'Ghana'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GI', 'Gibraltar'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GK', 'Guernsey'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GR', 'Greece'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GL', 'Greenland'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GD', 'Grenada'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GP', 'Guadeloupe'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GU', 'Guam'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GT', 'Guatemala'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GN', 'Guinea'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GW', 'Guinea-Bissau'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GY', 'Guyana'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('HT', 'Haiti'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('HM', 'Heard and Mc Donald Islands'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('HN', 'Honduras'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('HK', 'Hong Kong'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('HU', 'Hungary'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('IS', 'Iceland'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('IN', 'India'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('IM', 'Isle of Man'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('ID', 'Indonesia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('IR', 'Iran (Islamic Republic of)'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('IQ', 'Iraq'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('IE', 'Ireland'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('IL', 'Israel'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('IT', 'Italy'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CI', 'Ivory Coast'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('JE', 'Jersey'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('JM', 'Jamaica'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('JP', 'Japan'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('JO', 'Jordan'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('KZ', 'Kazakhstan'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('KE', 'Kenya'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('KI', 'Kiribati'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('KP', 'Korea, Democratic People''s Republic of'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('KR', 'Korea, Republic of'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('XK', 'Kosovo'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('KW', 'Kuwait'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('KG', 'Kyrgyzstan'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('LA', 'Lao People''s Democratic Republic'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('LV', 'Latvia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('LB', 'Lebanon'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('LS', 'Lesotho'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('LR', 'Liberia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('LY', 'Libyan Arab Jamahiriya'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('LI', 'Liechtenstein'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('LT', 'Lithuania'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('LU', 'Luxembourg'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MO', 'Macau'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MK', 'Macedonia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MG', 'Madagascar'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MW', 'Malawi'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MY', 'Malaysia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MV', 'Maldives'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('ML', 'Mali'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MT', 'Malta'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MH', 'Marshall Islands'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MQ', 'Martinique'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MR', 'Mauritania'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MU', 'Mauritius'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TY', 'Mayotte'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MX', 'Mexico'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('FM', 'Micronesia, Federated States of'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MD', 'Moldova, Republic of'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MC', 'Monaco'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MN', 'Mongolia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('ME', 'Montenegro'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MS', 'Montserrat'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MA', 'Morocco'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MZ', 'Mozambique'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MM', 'Myanmar'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('NA', 'Namibia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('NR', 'Nauru'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('NP', 'Nepal'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('NL', 'Netherlands'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('AN', 'Netherlands Antilles'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('NC', 'New Caledonia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('NZ', 'New Zealand'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('NI', 'Nicaragua'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('NE', 'Niger'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('NG', 'Nigeria'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('NU', 'Niue'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('NF', 'Norfolk Island'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('MP', 'Northern Mariana Islands'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('NO', 'Norway'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('OM', 'Oman'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('PK', 'Pakistan'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('PW', 'Palau'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('PS', 'Palestine'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('PA', 'Panama'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('PG', 'Papua New Guinea'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('PY', 'Paraguay'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('PE', 'Peru'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('PH', 'Philippines'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('PN', 'Pitcairn'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('PL', 'Poland'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('PT', 'Portugal'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('PR', 'Puerto Rico'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('QA', 'Qatar'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('RE', 'Reunion'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('RO', 'Romania'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('RU', 'Russian Federation'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('RW', 'Rwanda'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('KN', 'Saint Kitts and Nevis'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('LC', 'Saint Lucia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('VC', 'Saint Vincent and the Grenadines'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('WS', 'Samoa'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SM', 'San Marino'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('ST', 'Sao Tome and Principe'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SA', 'Saudi Arabia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SN', 'Senegal'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('RS', 'Serbia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SC', 'Seychelles'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SL', 'Sierra Leone'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SG', 'Singapore'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SK', 'Slovakia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SI', 'Slovenia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SB', 'Solomon Islands'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SO', 'Somalia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('ZA', 'South Africa'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GS', 'South Georgia South Sandwich Islands'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('ES', 'Spain'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('LK', 'Sri Lanka'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SH', 'St. Helena'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('PM', 'St. Pierre and Miquelon'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SD', 'Sudan'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SR', 'Suriname'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SJ', 'Svalbard and Jan Mayen Islands'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SZ', 'Swaziland'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SE', 'Sweden'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('CH', 'Switzerland'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('SY', 'Syrian Arab Republic'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TW', 'Taiwan'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TJ', 'Tajikistan'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TZ', 'Tanzania, United Republic of'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TH', 'Thailand'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TG', 'Togo'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TK', 'Tokelau'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TO', 'Tonga'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TT', 'Trinidad and Tobago'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TN', 'Tunisia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TR', 'Turkey'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TM', 'Turkmenistan'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TC', 'Turks and Caicos Islands'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('TV', 'Tuvalu'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('UG', 'Uganda'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('UA', 'Ukraine'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('AE', 'United Arab Emirates'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('GB', 'United Kingdom'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('US', 'United States'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('UM', 'United States minor outlying islands'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('UY', 'Uruguay'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('UZ', 'Uzbekistan'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('VU', 'Vanuatu'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('VA', 'Vatican City State'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('VE', 'Venezuela'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('VN', 'Vietnam'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('VG', 'Virgin Islands (British)'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('VI', 'Virgin Islands (U.S.)'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('WF', 'Wallis and Futuna Islands'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('EH', 'Western Sahara'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('YE', 'Yemen'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('ZR', 'Zaire'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('ZM', 'Zambia'  );
INSERT INTO COUNTRIES  (country_abbreviation,country_name) VALUES ('ZW', 'Zimbabwe'  );

COMMIT;