--generating tables and fulfill them with data


-- Generated by Oracle SQL Developer Data Modeler 17.4.0.355.2121
--   at:        2018-01-20 13:07:31 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

-- author: Wojciech Zielinski
-- BD project
-- SQL script for creating all of my tables

DROP TABLE airlines CASCADE CONSTRAINTS;

DROP TABLE airports CASCADE CONSTRAINTS;

DROP TABLE countries CASCADE CONSTRAINTS;

DROP TABLE discounts CASCADE CONSTRAINTS;

DROP TABLE flights CASCADE CONSTRAINTS;

DROP TABLE flights_reservations CASCADE CONSTRAINTS;

DROP TABLE reservations CASCADE CONSTRAINTS;

DROP TABLE tourists CASCADE CONSTRAINTS;

DROP SEQUENCE airlines_seq;
DROP SEQUENCE airports_seq;
DROP SEQUENCE countries_seq;
DROP SEQUENCE flights_seq;
DROP SEQUENCE reservations_seq;
DROP SEQUENCE tourists_seq;

CREATE TABLE airlines (
    airline_name      VARCHAR2(100) NOT NULL,
    airline_country   VARCHAR2(50),
    airline_id        INTEGER NOT NULL
);

ALTER TABLE airlines ADD CONSTRAINT airlines_pk PRIMARY KEY ( airline_name );

ALTER TABLE airlines ADD CONSTRAINT airlines__un UNIQUE ( airline_id );

CREATE TABLE airports (
    airport_code      CHAR(3) NOT NULL,
    airport_name      VARCHAR2(100) NOT NULL,
    airport_city      VARCHAR2(50),
    airport_country   VARCHAR2(50),
    airport_id        INTEGER NOT NULL
);

ALTER TABLE airports ADD CONSTRAINT airports_pk PRIMARY KEY ( airport_code );

ALTER TABLE airports ADD CONSTRAINT airports__un UNIQUE ( airport_name,
airport_id );

CREATE TABLE countries (
    country_abbreviation   CHAR(2) NOT NULL,
    country_name           VARCHAR2(50) NOT NULL,
    country_id             INTEGER NOT NULL
);

ALTER TABLE countries ADD CONSTRAINT countires_pk PRIMARY KEY ( country_name );

ALTER TABLE countries ADD CONSTRAINT countries__un UNIQUE ( country_id );

CREATE TABLE discounts (
    discount_id           INTEGER NOT NULL,
    reservation_id        INTEGER,
    discount_percentage   NUMBER(2,2) NOT NULL,
    discount_name         VARCHAR2(100)
);

ALTER TABLE discounts ADD CONSTRAINT discounts_pk PRIMARY KEY ( discount_id );

CREATE TABLE flights (
    flight_id                  INTEGER
        CONSTRAINT nnc_flights_fligth_id NOT NULL,
    airline_name               VARCHAR2(40) NOT NULL,
    flight_departure_time      TIMESTAMP(1) NOT NULL,
    flight_departure_airport   CHAR(3) NOT NULL,
    flight_arrival_time        TIMESTAMP(1) NOT NULL,
    flight_arrival_airport     CHAR(3) NOT NULL,
    flight_price               INTEGER NOT NULL
);

ALTER TABLE flights ADD CONSTRAINT flights_pk PRIMARY KEY ( flight_id );

CREATE TABLE flights_reservations (
    flight_id        INTEGER NOT NULL,
    reservation_id   INTEGER NOT NULL
);

ALTER TABLE flights_reservations ADD CONSTRAINT flights_reservations_pk PRIMARY KEY ( flight_id,
reservation_id );

CREATE TABLE reservations (
    reservation_id                  INTEGER NOT NULL,
    tourist_id                      INTEGER NOT NULL,
    reservation_number_of_flights   INTEGER DEFAULT 0 NOT NULL ,
    reservation_price               INTEGER DEFAULT 0 NOT NULL
);

ALTER TABLE reservations ADD CONSTRAINT reservations_pk PRIMARY KEY ( reservation_id );

CREATE TABLE tourists (
    tourist_id           INTEGER NOT NULL,
    tourist_first_name   VARCHAR2(30) NOT NULL,
    tourist_last_name    VARCHAR2(30) NOT NULL,
    tourist_country      VARCHAR2(50) NOT NULL
);

ALTER TABLE tourists ADD CONSTRAINT tourists_pk PRIMARY KEY ( tourist_id );

ALTER TABLE airlines
    ADD CONSTRAINT airlines_countries_fk FOREIGN KEY ( airline_country )
        REFERENCES countries ( country_name );

ALTER TABLE airports
    ADD CONSTRAINT airports_countires_fk FOREIGN KEY ( airport_country )
        REFERENCES countries ( country_name );

ALTER TABLE discounts
    ADD CONSTRAINT discounts_reservations_fk FOREIGN KEY ( reservation_id )
        REFERENCES reservations ( reservation_id )
            ON DELETE CASCADE;

ALTER TABLE flights
    ADD CONSTRAINT flights_airlines_fk FOREIGN KEY ( airline_name )
        REFERENCES airlines ( airline_name )
            ON DELETE CASCADE;

ALTER TABLE flights
    ADD CONSTRAINT flights_airports_arrival_fk FOREIGN KEY ( flight_arrival_airport )
        REFERENCES airports ( airport_code )
            ON DELETE CASCADE;

ALTER TABLE flights
    ADD CONSTRAINT flights_airports_departure_fk FOREIGN KEY ( flight_departure_airport )
        REFERENCES airports ( airport_code )
            ON DELETE CASCADE;

ALTER TABLE flights_reservations
    ADD CONSTRAINT flights_res_flights_fk FOREIGN KEY ( flight_id )
        REFERENCES flights ( flight_id )
            ON DELETE CASCADE;

ALTER TABLE flights_reservations
    ADD CONSTRAINT flights_res_res_fk FOREIGN KEY ( reservation_id )
        REFERENCES reservations ( reservation_id )
            ON DELETE CASCADE;

ALTER TABLE reservations
    ADD CONSTRAINT reservations_tourists_fk FOREIGN KEY ( tourist_id )
        REFERENCES tourists ( tourist_id );

ALTER TABLE tourists
    ADD CONSTRAINT tourists_countires_fk FOREIGN KEY ( tourist_country )
        REFERENCES countries ( country_name );



--********************************************************************************************************************************--
--********************************************************************************************************************************--
--TRIGGERS    TRIGGERS    TRIGGERS    TRIGGERS    TRIGGERS    TRIGGERS    TRIGGERS    TRIGGERS    TRIGGERS    TRIGGERS    TRIGGERS--
--********************************************************************************************************************************--
--********************************************************************************************************************************--

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--triger zapewniajacy nas o tym, ze nie dodamy zbyt dugiego lotu
CREATE OR REPLACE TRIGGER GoodFlightDetails
BEFORE INSERT ON flights
FOR EACH ROW
DECLARE
    
    interval_max INTERVAL DAY (2) TO SECOND := '0 15:00:00'; --length of flight may be maximum 15 hours
    interval_min INTERVAL DAY (2) TO SECOND := '0 1:00:00'; --length of flight may be minimum 1 hour
    
    --for another solution, maybe faster
    interval_new INTERVAL DAY (2) TO SECOND; --we will draw its value 
    interval_char VARCHAR2(12);
    hour_n NUMERIC(2); --we will draw new flight hour
    minute_n NUMERIC(2); --we will draw new flight minutes
    
     
    --to know range of randomization for airport and airline
    apc NUMERIC(4); --airport count 
    
    it1 NUMERIC (10) := 0; --to check how many times was in while loop with bad time
    
    --to store data of inserted flight
    f_id NUMERIC(4);
    dep_time TIMESTAMP(1);
    arr_time TIMESTAMP(1);
    dep_airp_id NUMERIC(4);
    arr_airp_id NUMERIC(4);
    dep_airp_c CHAR(3);   --departure airport code
    arr_airp_c CHAR(3);   --arrival airport code
    
    --to eventually randomize arrival time
    arr_year NUMERIC(4);
    arr_month NUMERIC(2);
    arr_day NUMERIC(2);
    arr_hour NUMERIC(2);
	arr_minute NUMERIC(2);
    arr_time_char CHAR(20);
    
    airl_name VARCHAR(100);
    p NUMERIC (4);
BEGIN
        
        --we want to check if just added time values and airports of flight  are correct
        dep_time := :new.flight_departure_time;
        arr_time := :new.flight_arrival_time;
        dep_airp_c := :new.flight_departure_airport;
        arr_airp_c := :new.flight_arrival_airport;
        
        SELECT airport_id into dep_airp_id from airports where airport_code = dep_airp_c;
        SELECT airport_id into arr_airp_id from airports where airport_code = arr_airp_c;
        
        --we will use it for eventually changing of arrival airport
        SELECT count(*) into apc from airports;
        
        --for eventually update in the end
        f_id := :new.flight_id;
        p := :new.flight_price;
        airl_name := :new.airline_name;
           
------------------------------------------------------------------------------------------------------------------------------------------------------------------    
        IF ( arr_time < dep_time + interval_min OR arr_time > dep_time + interval_max OR arr_airp_id = dep_airp_id OR p < 100 OR p > 2000) THEN
            
            if ( arr_time < dep_time + interval_min OR arr_time > dep_time + interval_max ) then 
                --new arrival time
                hour_n := dbms_random.value(1, 14);
                minute_n := dbms_random.value(0, 59);
                interval_char := to_char( '0 ' || hour_n || ':' || minute_n || ':00' );
                interval_new := interval_char;
                
                --new arrival time
                arr_time := dep_time + interval_new;
            end if;
            
            if ( arr_airp_id = dep_airp_id ) then
                --another randomization of arrival airport
                arr_airp_id := dbms_random.value(1,apc);
            end if;
            
            if( p < 100 OR p > 2000 ) then
                --randomization of flight price
                p := dbms_random.value(100,2000);
            end if;
            
            it1 := it1 + 1;
        END IF;
------------------------------------------------------------------------------------------------------------------------------------------------------------------

        --new arrival airport
        SELECT airport_code into arr_airp_c from airports where airport_id = arr_airp_id;
        
        IF it1 > 0 THEN
            INSERT INTO flights_auxiliary VALUES (f_id,airl_name,dep_time,dep_airp_c,arr_time,arr_airp_c,p);            
            :new.flight_id := f_id;
            :new.airline_name := airl_name;
            :new.flight_departure_time := dep_time;
            :new.flight_departure_airport := dep_airp_c;
            :new.flight_arrival_time := arr_time;
            :new.flight_arrival_airport := arr_airp_c;
            :new.flight_price := p;
        END IF;
                                        
        INSERT INTO KURCZAK VALUES (it1);   
END;
/
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


CREATE OR REPLACE TRIGGER change_reservation_price
AFTER INSERT ON flights_reservations
FOR EACH ROW
DECLARE 
    f_id NUMERIC(4);
    r_id NUMERIC(4);
    f_p INTEGER; --price of flight
    prev_r_p INTEGER; --price of reservation before adding this flight
    after_r_p INTEGER; --price of reservation after adding this flight
    prev_r_n INTEGER; --number of flights in reservation before adding this flight
    after_r_n INTEGER; --number of flights in reservation after adding this flight
BEGIN
    f_id := :new.flight_id; --flight_id of new flight reservation
    r_id := :new.reservation_id; --reservation_id of new flight reservation
    
    --
    SELECT reservation_price INTO prev_r_p FROM reservations where reservation_id = r_id;
    SELECT flight_price INTO f_p FROM flights where flight_id = f_id;
    SELECT reservation_number_of_flights INTO prev_r_n FROM reservations where reservation_id = r_id;
    
    after_r_p := prev_r_p + f_p;
    after_r_n := prev_r_n + 1;
    
    UPDATE reservations SET reservation_price = after_r_p, reservation_number_of_flights = after_r_n where reservation_id = r_id;    
    --after_r_p := 0;
    --prev_r_p := 0;
    --f_p := 0;
END;
/

-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------

--inserting countries into countries

DELETE FROM countries;

CREATE SEQUENCE countries_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 246;

INSERT INTO COUNTRIES VALUES ('AF', 'Afghanistan', countries_seq.nextval);
INSERT INTO COUNTRIES VALUES ('AL', 'Albania', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('DZ', 'Algeria', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('DS', 'American Samoa', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('AD', 'Andorra', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('AO', 'Angola', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('AI', 'Anguilla', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('AQ', 'Antarctica', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('AG', 'Antigua and Barbuda', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('AR', 'Argentina', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('AM', 'Armenia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('AW', 'Aruba', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('AU', 'Australia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('AT', 'Austria', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('AZ', 'Azerbaijan', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BS', 'Bahamas', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BH', 'Bahrain', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BD', 'Bangladesh', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BB', 'Barbados', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BY', 'Belarus', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BE', 'Belgium', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BZ', 'Belize', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BJ', 'Benin', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BM', 'Bermuda', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BT', 'Bhutan', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BO', 'Bolivia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BA', 'Bosnia and Herzegovina', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BW', 'Botswana', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BV', 'Bouvet Island', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BR', 'Brazil', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('IO', 'British Indian Ocean Territory', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BN', 'Brunei Darussalam', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BG', 'Bulgaria', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BF', 'Burkina Faso', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('BI', 'Burundi', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('KH', 'Cambodia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CM', 'Cameroon', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CA', 'Canada', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CV', 'Cape Verde', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('KY', 'Cayman Islands', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CF', 'Central African Republic', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TD', 'Chad', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CL', 'Chile', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CN', 'China', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CX', 'Christmas Island', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CC', 'Cocos (Keeling) Islands', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CO', 'Colombia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('KM', 'Comoros', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CG', 'Congo', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CK', 'Cook Islands', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CR', 'Costa Rica', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('HR', 'Croatia (Hrvatska)', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CU', 'Cuba', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CY', 'Cyprus', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CZ', 'Czech Republic', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('DK', 'Denmark', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('DJ', 'Djibouti', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('DM', 'Dominica', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('DO', 'Dominican Republic', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TP', 'East Timor', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('EC', 'Ecuador', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('EG', 'Egypt', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SV', 'El Salvador', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GQ', 'Equatorial Guinea', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('ER', 'Eritrea', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('EE', 'Estonia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('ET', 'Ethiopia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('FK', 'Falkland Islands (Malvinas)', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('FO', 'Faroe Islands', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('FJ', 'Fiji', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('FI', 'Finland', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('FR', 'France', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('FX', 'France, Metropolitan', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GF', 'French Guiana', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('PF', 'French Polynesia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TF', 'French Southern Territories', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GA', 'Gabon', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GM', 'Gambia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GE', 'Georgia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('DE', 'Germany', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GH', 'Ghana', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GI', 'Gibraltar', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GK', 'Guernsey', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GR', 'Greece', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GL', 'Greenland', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GD', 'Grenada', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GP', 'Guadeloupe', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GU', 'Guam', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GT', 'Guatemala', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GN', 'Guinea', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GW', 'Guinea-Bissau', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GY', 'Guyana', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('HT', 'Haiti', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('HM', 'Heard and Mc Donald Islands', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('HN', 'Honduras', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('HK', 'Hong Kong', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('HU', 'Hungary', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('IS', 'Iceland', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('IN', 'India', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('IM', 'Isle of Man', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('ID', 'Indonesia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('IR', 'Iran (Islamic Republic of)', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('IQ', 'Iraq', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('IE', 'Ireland', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('IL', 'Israel', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('IT', 'Italy', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CI', 'Ivory Coast', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('JE', 'Jersey', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('JM', 'Jamaica', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('JP', 'Japan', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('JO', 'Jordan', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('KZ', 'Kazakhstan', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('KE', 'Kenya', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('KI', 'Kiribati', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('KP', 'Korea, Democratic People''s Republic of', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('KR', 'Korea, Republic of', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('XK', 'Kosovo', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('KW', 'Kuwait', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('KG', 'Kyrgyzstan', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('LA', 'Lao People''s Democratic Republic', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('LV', 'Latvia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('LB', 'Lebanon', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('LS', 'Lesotho', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('LR', 'Liberia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('LY', 'Libyan Arab Jamahiriya', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('LI', 'Liechtenstein', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('LT', 'Lithuania', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('LU', 'Luxembourg', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MO', 'Macau', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MK', 'Macedonia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MG', 'Madagascar', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MW', 'Malawi', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MY', 'Malaysia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MV', 'Maldives', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('ML', 'Mali', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MT', 'Malta', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MH', 'Marshall Islands', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MQ', 'Martinique', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MR', 'Mauritania', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MU', 'Mauritius', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TY', 'Mayotte', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MX', 'Mexico', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('FM', 'Micronesia, Federated States of', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MD', 'Moldova, Republic of', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MC', 'Monaco', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MN', 'Mongolia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('ME', 'Montenegro', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MS', 'Montserrat', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MA', 'Morocco', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MZ', 'Mozambique', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MM', 'Myanmar', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('NA', 'Namibia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('NR', 'Nauru', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('NP', 'Nepal', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('NL', 'Netherlands', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('AN', 'Netherlands Antilles', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('NC', 'New Caledonia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('NZ', 'New Zealand', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('NI', 'Nicaragua', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('NE', 'Niger', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('NG', 'Nigeria', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('NU', 'Niue', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('NF', 'Norfolk Island', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('MP', 'Northern Mariana Islands', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('NO', 'Norway', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('OM', 'Oman', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('PK', 'Pakistan', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('PW', 'Palau', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('PS', 'Palestine', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('PA', 'Panama', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('PG', 'Papua New Guinea', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('PY', 'Paraguay', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('PE', 'Peru', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('PH', 'Philippines', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('PN', 'Pitcairn', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('PL', 'Poland', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('PT', 'Portugal', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('PR', 'Puerto Rico', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('QA', 'Qatar', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('RE', 'Reunion', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('RO', 'Romania', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('RU', 'Russian Federation', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('RW', 'Rwanda', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('KN', 'Saint Kitts and Nevis', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('LC', 'Saint Lucia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('VC', 'Saint Vincent and the Grenadines', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('WS', 'Samoa', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SM', 'San Marino', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('ST', 'Sao Tome and Principe', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SA', 'Saudi Arabia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SN', 'Senegal', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('RS', 'Serbia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SC', 'Seychelles', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SL', 'Sierra Leone', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SG', 'Singapore', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SK', 'Slovakia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SI', 'Slovenia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SB', 'Solomon Islands', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SO', 'Somalia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('ZA', 'South Africa', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GS', 'South Georgia South Sandwich Islands', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('ES', 'Spain', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('LK', 'Sri Lanka', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SH', 'St. Helena', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('PM', 'St. Pierre and Miquelon', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SD', 'Sudan', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SR', 'Suriname', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SJ', 'Svalbard and Jan Mayen Islands', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SZ', 'Swaziland', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SE', 'Sweden', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('CH', 'Switzerland', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('SY', 'Syrian Arab Republic', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TW', 'Taiwan', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TJ', 'Tajikistan', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TZ', 'Tanzania, United Republic of', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TH', 'Thailand', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TG', 'Togo', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TK', 'Tokelau', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TO', 'Tonga', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TT', 'Trinidad and Tobago', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TN', 'Tunisia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TR', 'Turkey', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TM', 'Turkmenistan', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TC', 'Turks and Caicos Islands', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('TV', 'Tuvalu', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('UG', 'Uganda', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('UA', 'Ukraine', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('AE', 'United Arab Emirates', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('GB', 'United Kingdom', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('US', 'United States', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('UM', 'United States minor outlying islands', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('UY', 'Uruguay', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('UZ', 'Uzbekistan', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('VU', 'Vanuatu', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('VA', 'Vatican City State', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('VE', 'Venezuela', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('VN', 'Vietnam', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('VG', 'Virgin Islands (British)', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('VI', 'Virgin Islands (U.S.)', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('WF', 'Wallis and Futuna Islands', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('EH', 'Western Sahara', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('YE', 'Yemen', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('ZR', 'Zaire', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('ZM', 'Zambia', countries_seq.nextval );
INSERT INTO COUNTRIES VALUES ('ZW', 'Zimbabwe', countries_seq.nextval );

-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------

--insert airports
DELETE FROM airports;

CREATE SEQUENCE airports_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE;


INSERT INTO airports VALUES ('LHR', 'Heathrow Airport', 'London', 'United Kingdom', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('FRA', 'Frankfurt Airport', 'Frankfurt', 'Germany', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('JFK', 'John F. Kennedy International Airport', 'New York', 'United States', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('EWR', 'Newark Liberty International Airport', 'Newark', 'United States', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('LAS', 'Mccarran International Airport', 'Las Vegas', 'United States', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('WAW', 'Warsaw Chopin Airport', 'Warsaw', 'Poland', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('WMI', 'Warsaw Modlin Airport', 'Nowy Dwór Mazowiecki', 'Poland', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('WRO', 'Copernicus Airport Wroclaw', 'Wroclaw', 'Poland', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('LUZ', 'Lublin Airport', 'Œwidnik', 'Poland', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('BCN', 'Barcelona-El Prat Airport', 'Barcelona', 'Spain', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('MAD', 'Adolfo Suarez Madrid-Barajas Airport', 'Madrid', 'Spain', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('OPO', 'Francisco Sa Carneiro Airport', 'Porto', 'Portugal', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('TFN', 'Tenerife North Airport', 'San Cristobal de La Laguna', 'Spain', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('TFS', 'Tenerife South Airport', 'Granadilla de Abona', 'Spain', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('CIA', 'Ciampino-G.B. Pastine International Airport', 'Rome', 'Italy', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('FCO', 'Leonardo da Vinci-Fiumicino Airport', 'Rome', 'Italy', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('PRG', 'Vaclav Havel Airport Prague', 'Prague', 'Czech Republic', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('BUD', 'Budapest Ferenc Liszt International Airport', 'Budapest', 'Hungary', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('ZAG', 'Franjo Tudman Airport', 'Zagreb', 'Croatia (Hrvatska)', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('GDN', 'Gdansk Lech Walesa Airport', 'Gdañsk', 'Poland', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('POZ', 'Poznañ-£awica Henryk Wieniawski Airport', 'Je¿yce', 'Poland', airports_seq.NEXTVAL);
INSERT INTO airports VALUES ('SZZ', 'Solidarity Szczecin-Goleniów Airport', 'Goleniów', 'Poland', airports_seq.NEXTVAL);

--Insert airlines
DELETE FROM airlines;
CREATE SEQUENCE airlines_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE;

INSERT INTO airlines VALUES ('TAM Linhas Aereas', 'Brazil', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Wizz Air', 'Hungary', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('LOT Polish Airlines', 'Poland', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Swiss International Airlines', 'Switzerland', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Ryanair', 'Ireland', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Saudi Arabian Airlines', 'Saudi Arabia', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Lufthansa', 'Germany', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('British Airways', 'United Kingdom', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Air France', 'France', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Turkish Airlines', 'Turkey', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Brussels Airlines', 'Belgium', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Croatia Airlines', 'Croatia (Hrvatska)', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Delta Air Lines', 'United States', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('United Airlines', 'United States', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Southwest Airlines', 'United States', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('American Airlines', 'United States', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('China Southern Airlines', 'China', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('US Airways', 'United States', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('China Eastern Airlines', 'China', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('KLM', 'Netherlands', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Air Berlin', 'Germany', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('easyJet', 'United Kingdom', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Emirates', 'United Arab Emirates', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Air Canada', 'Canada', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('China Western Airlines', 'China', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('China Northest Airlines', 'China', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Singapore Airlines', 'Singapore', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('All Nippon Airways', 'Japan', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('EgyptAir', 'Egypt', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Quantas Group', 'Australia', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Air Moldova', 'Moldova, Republic of', airlines_seq.NEXTVAL);
INSERT INTO airlines VALUES ('Virgin Atlantic Airways', 'United Kingdom', airlines_seq.NEXTVAL);

-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------

--Insert tourists
set serveroutput on format wrapped;
set define off;

DELETE FROM tourists;


CREATE SEQUENCE tourists_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE;

DECLARE
    TYPE TAB_FIRST_NAME_M IS TABLE OF VARCHAR2(20);
    first_name_m TAB_FIRST_NAME_M;
    TYPE TAB_FIRST_NAME_W IS TABLE OF VARCHAR2(20);
    first_name_w TAB_FIRST_NAME_W;
    TYPE TAB_LAST_NAME IS TABLE OF VARCHAR2(20);
    last_name TAB_LAST_NAME;
    
    c_id_min INTEGER;
    c_id_max INTEGER;
    
    fnm NUMBER(5);
    fnw NUMBER(5);
    lnm NUMBER(5);
    lnw NUMBER(5);
    cm NUMBER(5);
    cw NUMBER(5);

BEGIN
    SELECT MIN(country_id) INTO c_id_min from countries;
    SELECT MAX(country_id) INTO c_id_max from countries;

    first_name_m := TAB_FIRST_NAME_M (  'Jan', 'Stanis³aw', 'Andrzej', 'Józef', 'Tadeusz', 'Jerzy', 'Zbigniew', 'Krzysztof', 'Henryk', 
                                        'Ryszard', 'Kazimierz', 'Marek', 'Marian', 'Piotr', 'Janusz', 'W³adys³aw', 'Adam', 'Wies³aw', 
                                        'Zdzis³aw', 'Edward', 'Mieczys³aw', 'Roman', 'Miros³aw', 'Grzegorz', 'Czes³aw', 'Dariusz', 
                                        'Wojciech', 'Jacek', 'Eugeniusz', 'Tomasz', 'Stefan', 'Zygmunt', 'Leszek', 'Bogdan', 'Antoni', 
                                        'Pawe³½', 'Franciszek', 'S³awomir', 'Waldemar', 'Jaros³aw', 'Robert', 'Mariusz', 'W³odzimierz', 
                                        'Micha³½', 'Zenon', 'Bogus³aw', 'Witold', 'Aleksander', 'Bronis³aw', 'Wac³aw', 'Boles³aw', 
                                        'Ireneusz', 'Maciej', 'Artur', 'Edmund', 'Marcin', 'Lech', 'Karol', 'Rafaï¿½', 'Arkadiusz', 'Leon', 
                                        'Sylwester', 'Lucjan', 'Julian', 'Wiktor', 'Romuald', 'Bernard', 'Ludwik', 'Feliks', 'Alfred', 
                                        'Alojzy', 'Przemys³aw', 'Cezary', 'Daniel', 'Miko³aj', 'Ignacy', 'Les³aw', 'Rados³aw', 'Konrad', 
                                        'Bogumi³½', 'Szczepan', 'Gerard', 'Hieronim', 'Krystian', 'Leonard', 'Wincenty', 'Benedykt', 
                                        'Hubert', 'Sebastian', 'Norbert', 'Adolf', '£ukasz', 'Emil', 'Teodor', 'Rudolf', 'Joachim', 'Jakub',
                                        'Walenty', 'Alfons', 'Damian', 'Rajmund', 'Szymon', 'Zygfryd','Leopold', 'Remigiusz', 'Florian', 
                                        'Konstanty', 'Augustyn', 'Albin', 'Bohdan', 'Dominik', 'Gabriel', 'Teofil', 'Brunon', 
                                        'Juliusz', 'Walerian', 'Bart³omiej', 'Fryderyk', 'Eryk', 'Anatol', 'Maksymilian', 'Gustaw', 
                                        'Aleksy', 'Longin', 'Bartosz', 'Wilhelm', 'Ferdynand', 'Erwin', 'Klemens', 'Lechos³aw', 'Ernest', 
                                        'Seweryn', 'Herbert', 'Albert', 'B³a¿ej', 'Izydor', 'Dionizy', 'Edwin', 'Ginter', 'Adrian', 'Mateusz',
                                        'Walter', 'Helmut', 'Bazyli', 'Marceli', 'Sergiusz', 'Bonifacy', 'Werner', 'Eligiusz', 'Wawrzyniec');
                                        
    first_name_w := TAB_FIRST_NAME_W (  'Maria', 'Krystyna', 'Anna', 'Barbara', 'Teresa', 'El¿bieta', 'Janina', 'Zofia', 'Jadwiga', 'Danuta', 
                                        'Halina', 'Irena', 'Ewa', 'Ma³gorzata', 'Helena', 'Gra¿yna', 'Bo¿ena', 'Stanis³awa', 'Jolanta', 'Marianna', 
                                        'Urszula', 'Wanda', 'Alicja', 'Dorota', 'Agnieszka', 'Beata', 'Katarzyna', 'Joanna', 'Wies³awa', 'Renata', 
                                        'Iwona', 'Genowefa', 'Kazimiera', 'Stefania', 'Hanna', 'Lucyna', 'Józefa', 'Alina', 'Miros³awa', 'Aleksandra', 
                                        'W³adys³awa', 'Henryka', 'Czes³awa', 'Lidia', 'Regina', 'Monika', 'Magdalena', 'Bogumi³a', 'Marta', 'Marzena', 
                                        'Leokadia', 'Mariola', 'Bronis³awa', 'Aniela', 'Bogus³awa', 'Eugenia', 'Izabela', 'Cecylia', 'Emilia', '£ucja', 
                                        'Gabriela', 'Sabina', 'Zdzis³awa', 'Agata', 'Edyta', 'Aneta', 'Daniela', 'Wioletta', 'Sylwia', 'Weronika', 
                                        'Antonina', 'Justyna', 'Gertruda', 'Mieczys³awa', 'Franciszka', 'Rozalia', 'Zuzanna', 'Natalia', 'Celina', 
                                        'Ilona', 'Alfreda', 'Wiktoria', 'Olga', 'Wac³awa', 'Ró¿a', 'Karolina', 'Bernadeta', 'Julia', 'Michalina', 
                                        'Adela', 'Ludwika', 'Honorata', 'Aldona', 'Eleonora', 'Violetta', 'Felicja', 'Walentyna', 'Pelagia', 
                                        'Apolonia', 'Brygida', 'Zenona', 'Izabella', 'Romana', 'Zenobia', 'Waleria', 'Anita', 'Bo¿enna', 'Romualda',
                                        'Marzanna', 'Anastazja', 'Kamila', 'Aurelia', 'Ewelina', 'Ludmi³a', 'Hildegarda', 'Teodozja', 'Feliksa', 
                                        'Nina', 'Paulina', 'Longina', 'Julianna', 'Klara', 'Marlena', 'Teodora', 'Leonarda', 'Ryszarda', 'Liliana', 
                                        'Kinga', 'Lilianna', 'Albina', 'Elwira', 'Gizela', 'Boles³awa', 'Otylia', 'Karina', 'Arleta', 'Marzenna', 
                                        'Melania', 'Kornelia', 'Salomea', 'Adelajda', 'Eryka', 'Dominika', 'S³awomira', 'Donata', 'Eliza', 'Tamara', 
                                        'Zyta', 'Bernadetta', 'Nadzieja');
                                        
    last_name := TAB_LAST_NAME (        'Zieliñski', 'Rogalski', 'Binkiewicz', 'Pawlak', 'Kowalski', 'Stawiarski', 'Borowicz', 'Talarowski', 'Wójcik', 
                                        'Palmowski', 'Sidor', 'Kowalczyk', 'Górski', 'Kowalski', 'Wisniewski', 'Kowalczyk', 'Kamiñski', 'Lewandowski', 
                                        'Szymañski', 'WoŸniak', 'Jankowski', 'Mazur', 'Wojciechowski', 'Kwiatkowski', 'Krawczyk', 'Kaczmarek', 'Piotrowski', 
                                        'Grabowski', 'Nowakowski', 'Wieczorek', 'Wróbel', 'Dudek', 'Adamczyk', 'Majewski', 'Nowicki', 'Olszewski', 'Malinowski',
                                        'Pawlak', 'Witkowski', 'Walczak', 'Sikora', 'Rutkowski', 'Baran', 'Michalak', 'Szewczyk', 'Ostrowski', 'Tomaszewski', 
                                        'Szewczyk', 'Ostrowski', 'Majewski', 'Tarasiuk', 'Katarzyñski', 'Jachimowski', 'Ludwig', 'Sk³odowski', 'Szopiñski', 'Zubek', 
                                        '£yszczarz', 'Bernat', 'Pietrucha', 'Targosz', 'Weso³ek', 'Brych', 'W¹sowicz', 'Dankowski', '£abêcki', 'Wróbel', 'Rojek', 
                                        'Lenart', 'Ziêba', 'Kotarba', 'Grzyb', 'Pa³ka', 'Maækiewicz', 'Bazan', 'Kwaœny', 'Burski', 'Puk', 'Nowocieñ', 'Koryciñski', 
                                        'Kap³on', 'Tomczak', 'Maciaszczyk', 'Pêczek', 'Pliszka', 'Szypu³a', 'Dygas', 'Borys', 'Wojtkiewicz', 'Konefa³', 'Pindel', 
                                        'Karolak', 'Styczyñski', 'Szczotka', 'Lewandowski', 'Maci¹g', 'Juchniewicz', 'Kurzawa', 'Dzier¿anowski', 'Klepacz', 
                                        'Prokopowicz', 'Gnatowski', 'Matuszewski', 'Parzych', 'Nowek', 'Kuœ', 'Myœliñski', 'Ferenc', 'Bera', 'Rudzki', 'Zdunek', 
                                        'Kruczkowski', 'Sobczuk', 'Wyka', 'Szkudlarek', 'Boratyñski', 'Ko¿uch', 'Szot', 'Babik', 'Tylkowski', 'Meller', 'S³aby', 
                                        'Niemczyk', 'Jarmo³owicz', 'Makuch', 'Œwierczek', 'Stefanek', 'Brzostek', 'Kusy', 'Zbroja', 'Depa', 'Kmiecik', 'Musio³', 
                                        'Bolesta', 'Sobczyk', 'Kozie³', 'Pamu³a', 'Milewski', 'Kaniowski', 'Dziedzic', 'O¿arowski', 'M³ynarski', 'Szul', 'Lubañski', 
                                        'G³ogowski', 'Che³miñski', 'Pelczar', 'Krzemiñski', 'Opoka', 'Klima', 'Majchrzyk', 'Szumilas', 'Hoffmann', 'Perliñski', 
                                        'Adamczuk', 'Potempa', 'Micha³ek', 'Pietruczuk', 'Walkowicz', 'Kosek', 'Przepiórka', 'Kolenda', 'Dobosz', 'Tomaszewicz', 
                                        'Rychel', 'Orszulak', 'Czapliñski', 'Klimaszewski', 'R¹czkowski', '¯uraw', 'Krych', 'M³yñski', 'Mazgaj', 'Podbielski', 
                                        'Jurczyk', 'Dworakowski', 'Pawlus', 'Kosicki', 'Urbanek', 'Fr¹czek', 'Zagórski', 'Rosó³', 'Gac', 'Synowiec', 'Garbowski', 
                                        'Gontarz', 'Szuster', 'Ró¿ycki', 'Kmieciak', 'Berliñski', 'Zwierzchowski', 'Dyjak', 'Wieliczko', 'Kêsy', 'Koba', 'Trzaski', 
                                        '£abuda', 'Kozik', 'Orczyk', 'Moczulski', 'Bala', 'Linek', 'Dubas', 'Sobkowiak', 'Zychowicz', 'Dominiczak', 'Ciechomski', 
                                        'Rojewski', 'Sulewski', 'Ryszkowski', 'Mrozek', 'Pucek', 'Cyganek', 'Cieœlak', 'Piekut', 'Œl¹zak', 'KaŸmierczak', 'Krynicki', 
                                        'Wantuch', 'Andruszkiewicz', 'Tymiñski', 'Seroczyñski', 'Fiedorowicz', 'Nita', 'Kozakiewicz', 'Waœko', 'Filipski', 'KoŸmiñski', 
                                        'Izydorczyk', '£yczko', 'Ca³a', 'Stolc', 'Stolarski', 'Matulewicz', 'Modliñski', 'Staszczyk', 'Jaroszyñski', 'Sajdak', 'Rybka', 
                                        'Ga³kowski', 'Narloch', 'Bodnar', 'Wieczorek', 'Raczek', 'Miszczuk', 'Ksiê¿opolski', 'M¹czyñski', 'Klasa', 'P¹czek', 'Lenarczyk', 
                                        'Olszañski', 'Sas', 'Tracz', 'Greñ', 'Szczyrba', 'Marchlewski', 'Maciaszek', 'K³os', 'Jaskot', 'Ceglarski', 'Zoñ', 'Nitka', 
                                        'Pêkalski', 'Golis', 'Knopik', 'Dro¿d¿', 'Waœkiewicz', 'Jaruga', 'Pawiñski', 'Kraœnicki', 'Laski', 'Kiedrowski', 'Cieœluk', 
                                        'Wolf', 'Krysa', 'Czeka³a', 'Mierzwa', 'Wala', 'Dolny', 'Bartosik', 'Sobala', 'Chrapek', 'Strach', 'Niedzielski', 'Sierocki', 
                                        'Kura', 'Baj', 'Czy¿yk', 'Lupa', 'Panas', 'Malicki', 'Bobiñski', 'Idziak', 'Kochanek', 'Iwaszko', 'Grenda', 'Paluszek', 
                                        'Zborowski', 'Karolczyk', 'Ziemba', 'Florczak', 'Kurzak', 'Tobo³a', 'Dembowski', 'Klusek', 'Wilga', 'Kudliñski', 'Ko³ecki', 
                                        'Kêdzior', 'Rosik', 'Buga³a', 'Witkowski', 'NiedŸwiedŸ', 'Grzeœ', 'Bojarski', 'Wasilewski', 'Szczygielski', 'Gorczyñski', 
                                        'Filipiuk', 'Ceg³owski', 'Chmielewski', 'Wo³owiec', 'Kozio³ek', 'Korzeniowski', 'Noga', 'K³ak', 'Orliñski', 'Krzeœniak', 
                                        'Przygoda', 'Witczak', 'Pawlas', 'Ratajczak', 'Konieczna', 'Dêbkowski', 'Lewandowicz', 'Treder', 'Borowczak', 'Gajda', 'Gaj', 
                                        'Borowiak', 'Pajewski', 'Anio³', 'Starczewski', 'Kozanecki', 'Boczar', 'Paœ', 'Grêda', 'Goœciniak', 'Gawron', 'Kwapisz', 'Soboñ', 
                                        'Koby³ecki', 'Zawada', 'Kubik', 'Maliñski', 'Jamka', 'Bartoszuk', 'Kryszak', 'Wojdy³o', 'Pra³at', 'Modzelewski', 'Bator', 'Borucki', 
                                        'Bogdañski', 'Zduniak', 'Talar', 'Kanclerz', 'Kurkowski', 'GoŸdzik', 'Ozimek', 'Marcinkowski', 'Jagodziñski', 'Deska', 'Chojecki', 
                                        'Koliñski', 'S³owiñski', 'Suchan', 'Ko³odziejski', 'Tokarski', 'O³dak', 'Chmieliñski', 'Pyra', 'Chmielowski', 'WoŸniak', 'Filipczak', 
                                        'Soszka', 'Kobylañski', 'Szulik', 'Biskupski', 'Okoniewski', 'Kêski', 'Roman', 'Korona', 'Guba³a', 'Surmacz', 'Mo¿d¿eñ', 'Gralak', 
                                        'Zaleski', '¯urowski', 'Ka³a', 'Bogdanowicz', 'Klimkiewicz', 'Kopeæ', 'Bartosz', 'Pisarczyk', 'Hawryluk', 'Wolnik', 'Rakoczy', 
                                        'Otto', 'Wiecha', 'Latawiec', 'Koperski', 'Krzysiek', 'Binek', 'Przytu³a', 'Nowok', 'Sawczuk', 'Golik', 'Janiczek', 'Przerwa', 
                                        'Rosiñski', 'Werner', 'Guzek', 'B³asiak', 'W³odarek', 'Karolczak', 'Wieloch', 'Mendyk', 'Kornas', 'Zdanowski', 'Bochenek', 
                                        'Adamczak', 'Przywara', 'Walaszek', 'JóŸwicki', 'Witt', 'Ludwikowski', 'Domagalski', 'Œmia³ek', 'Pieprzyk', 'Pikulski', 'Motyl', 
                                        'Siwak', 'Mrozik', 'Karpiuk', 'Walczyk', 'Go³da', 'Mazur', 'Waœ', 'Walaszczyk', 'Mielnik', 'Czerwonka', 'Dybowski', 'P³awecki', 
                                        'Kobus', 'Marks', 'Karczewski', 'Masternak', 'Sawka', 'Polañski', 'Wojtyczka', 'Maciejewski', 'Kmita', 'Dzida', 'Buka³a', 'Kluz', 
                                        'Lasak', 'Paziewski', 'Sulej', 'Hryniewicz', 'Czarnota', 'Jasiewicz', 'O³dakowski', 'Winnicki', 'B³aszkowski', 'Wojtasiak', 
                                        'Jedliñski', 'Gosk', 'Kluk', 'Ga³czyñski', 'Piechowiak', 'Mocek', 'Ogrodowski', 'Stawski', 'Gierczak', 'Skoczeñ', 'Barabasz', 
                                        'P³achta', 'Popio³ek', 'Sacha', 'Rêkas', 'Barczyk', 'Giziñski', 'Korzeniewski', 'Koch', 'Kluza', 'Papie¿', 'Kokociñski', 'Ossowski', 
                                        'Migda³', 'Gad', 'Skórski', 'S³owik', 'Komar', 'Rak', 'Cisek', 'Syrek', 'Kordek', 'Bauer', 'Sidorowicz', 'Choma', 'Marcinkiewicz', 
                                        'Kwidziñski', 'Przybyszewski', 'Gorczyca', 'Kokot', 'Grabowski', 'Molik', 'Burzyñski', 'Jaskó³ka', 'Krzak', 'Nowosad', '£upiñski', 
                                        'Zió³kowski', 'Pasek', 'Zawistowski', 'Tokarz', 'Babiak', 'Polowczyk', 'Olbryœ', 'Pietruszewski', 'Kuœnierz', 'Gracz', 'Suchomski', 
                                        'Oleœ', 'Gawryluk', 'Ujma', 'Mróz', '£yczkowski', 'JóŸwiak', 'Nikodem', 'Gancarczyk', 'Skóra', 'Palacz', 'Kuc', 'Marczak', 
                                        'Martyniuk', 'Kowalewski', 'Konarzewski', 'Adler');  

    
    FOR i IN 1..1500 LOOP
        fnm := dbms_random.value(1,first_name_m.count); --150
        fnw := dbms_random.value(1,first_name_w.count); --150
        lnm := dbms_random.value(1,last_name.count); --550
        lnw := dbms_random.value(1,last_name.count); --550
        cm := dbms_random.value(c_id_min,c_id_max);
        cw := dbms_random.value(c_id_min,c_id_max);
        
        INSERT INTO tourists (tourist_id, tourist_first_name, tourist_last_name, tourist_country)
        VALUES (tourists_seq.NEXTVAL, first_name_m(fnm), last_name(lnm), ( SELECT country_name FROM countries WHERE country_id = cm ) );
        
        INSERT INTO tourists (tourist_id, tourist_first_name, tourist_last_name, tourist_country   )
        VALUES (tourists_seq.NEXTVAL, first_name_w(fnm), last_name(lnw), ( SELECT country_name FROM countries WHERE country_id = cw ) ); 
    END LOOP;
    
END;
/

-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------

--insert flight

set serveroutput on format wrapped;
set define off;

DELETE FROM flights;



CREATE SEQUENCE flights_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE;


DECLARE
    airl_id NUMERIC(4); --airline_id
    price NUMERIC(4); 
    
    interval_max INTERVAL DAY (2) TO SECOND := '0 15:00:00'; --length of flight may be maximum 15 hours
    interval_min INTERVAL DAY (2) TO SECOND := '0 1:00:00'; --length of flight may be minimum 1 hour
    
    --for randomize airports
    dep_airp_id NUMERIC(4);
    arr_airp_id NUMERIC(4);
    
    --for randomize airports
    dep_airp_c CHAR(3);   --departure airport
    arr_airp_c CHAR(3);   --arrival airport
    
    --to know range of randomization for airport and airline
    alc NUMERIC(4); --airline count
    apc NUMERIC(4); --airport count 
    
    it1 NUMERIC (10) := 0; --to check how many times was in while loop with bad time
    
    --to randomize departure time
    dep_year NUMERIC(4);
    dep_month NUMERIC(2);
    dep_day NUMERIC(2);
    dep_hour NUMERIC(2);
	dep_minute NUMERIC(2);
    dep_time_char CHAR(20);
    dep_time TIMESTAMP(1);
    
    --to randomize arrival time
    arr_year NUMERIC(4);
    arr_month NUMERIC(2);
    arr_day NUMERIC(2);
    arr_hour NUMERIC(2);
	arr_minute NUMERIC(2);
    arr_time_char CHAR(20);
    arr_time TIMESTAMP(1);
    
BEGIN
	FOR i IN 1..100 LOOP 
    
        SELECT count(*) into alc from airlines;
        SELECT count(*) into apc from airports;
    
        airl_id := dbms_random.value(2, alc);
        price := dbms_random.value(100,2000);
        
        dep_airp_id := dbms_random.value(2,apc);
        arr_airp_id := dbms_random.value(2,apc);
        
        --randomization of departure time
        dep_year := 2018;
		dep_month := dbms_random.value(2,4);
        if(dep_month in (1,3,5,7,8,10,12)) then dep_day := dbms_random.value(1,31); end if;
        if(dep_month in (4,6,9,11)) then dep_day := dbms_random.value(1,30); end if;
        if(dep_month in (2)) then dep_day := dbms_random.value(1,28); end if;
        dep_hour := dbms_random.value(0,23);
        dep_minute := dbms_random.value(0,59);
        dep_time_char := to_char(dep_year) || to_char(dep_month,'99') || to_char(dep_day,'99') || to_char(dep_hour,'99') || to_char(dep_minute,'99');
        
        --randomization of arrival time
        arr_year := 2018;
		arr_month := dbms_random.value(2,4);
        if(arr_month in (1,3,5,7,8,10,12)) then arr_day := dbms_random.value(1,31); end if;
        if(arr_month in (4,6,9,11)) then arr_day := dbms_random.value(1,30); end if;
        if(arr_month in (2)) then arr_day := dbms_random.value(1,28); end if;
        arr_hour := dbms_random.value(0,23);
        arr_minute := dbms_random.value(0,59);
        arr_time_char := to_char(arr_year) || to_char(arr_month,'99') || to_char(arr_day,'99') || to_char(arr_hour,'99') || to_char(arr_minute,'99');
        
        dep_time := to_date(dep_time_char,'yyyymmddhh24mi');
        arr_time := to_date(arr_time_char,'yyyymmddhh24mi');
            
        --randomization of airports
        SELECT airport_code into dep_airp_c from airports where airport_id = dep_airp_id;
        SELECT airport_code into arr_airp_c from airports where airport_id = arr_airp_id;
        
        INSERT INTO flights VALUES  (   flights_seq.NEXTVAL, 
                                        (SELECT airline_name FROM airlines WHERE airline_id = airl_id), 
                                        dep_time, dep_airp_c,arr_time,arr_airp_c,price);                                 
	END LOOP;
END;
/

-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------

--insert into reservations


set serveroutput on format wrapped;
set define off;

DELETE FROM reservations;
DELETE FROM flights_reservations;


CREATE SEQUENCE reservations_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE;


DECLARE
    t_id NUMERIC(4); --tourist_id  
    f_id NUMERIC(4); --flight_id
    r_id NUMERIC(4); --reservation_id
    
    f_count NUMERIC(4); --to randomize tourist id
    f_min_id NUMERIC (4);
    f_max_id NUMERIC (4);
    
    t_count NUMERIC(4); --to randomize tourist id
    t_min_id NUMERIC (4);
    t_max_id NUMERIC (4);
    
BEGIN
	FOR i IN 1..1000 LOOP 
    
    
        SELECT count(*) into t_count from tourists;
        SELECT min(tourist_id) into t_min_id from tourists;
        SELECT MAX(tourist_id) into t_max_id from tourists;
        
        SELECT count(*) into f_count from flights;
        SELECT min(flight_id) into f_min_id from flights;
        SELECT MAX(flight_id) into f_max_id from flights;
        
    
        t_id := dbms_random.value(t_min_id, t_max_id); --random tourist_id
        f_id := dbms_random.value(f_min_id, f_max_id); --random flight_id
        --in trigger we will check if it is valid tourist id      
        
        r_id := reservations_seq.NEXTVAL;
        
        INSERT INTO reservations ( reservation_id, tourist_id ) VALUES  ( r_id, t_id);
        INSERT INTO flights_reservations VALUES (f_id,r_id);
        
        IF (f_id % 10) = 0 THEN
            INSERT INTO flights_reservations VALUES (f_id-1,r_id);
        END IF;
        
	END LOOP;
END;
/


commit;

-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------
